<h1>Sveltekit - Pocketbase - UIkit - Starterkit</h1>

This is a starterkit (template app) where we bundled:

<ul class="uk-list uk-list-disc">
    <li><a href="https://kit.svelte.dev/" target="_blank">Sveltekit</a></li>
    <li><a href="https://pocketbase.io/" target="_blank">Pocketbase</a> on <a href="https://pockethost.io/" target="_blank">Pockethost</a></li>
    <li><a href="https://getuikit.com/" target="_blank">UIkit</a></li>
</ul>

<p>This combination of frameworks and database is suitable for SMB web apps.</p>

<h2>Usage</h2>
<p>
Download or git clone this repo. 

Open your CLI in the folder where you downloaded and unpacked the files.
</p>
<ul class="uk-list uk-list-disc">
    <li>Use: npm install to install all dependencies</li>
    <li>Use: npm run dev to start the app</li>
</ul>


<h2>Config</h2>
<p>
To make this app work there are a few simple things to do.
</p>

<h3>Routes</h3>
<p>
Routes will be autogenerated based on the folders in /src/routes/ that contain a +page.svelte file. So everytime you 
create a folder with a +page.svelte file in it, that route will be auto displayed in the sidebar.
</p>

<h3>Environment variables</h3>
<p>
To make the app work with the data you need a pocketbase instance somewhere. We host ours on <a href="https://pockethost.io/" target="_blank">pockethost</a>.
<br /><br />
Create a .env file with an entry: 
<br />
VITE_POCKETBASE_URL=https://myinstance.pockethost.io/
<br /><br />
After adding this, your app is almost ready to use.

Next, create a pocketbase instance and use the url of that instance in the .env file. Then you first create a user manually in the pocketbase users collection. 
After that you can log in to this app with that account.
</p>

<em>This bundle was created by Patrick Tehubijuluw (creatuluw at gmail dot com).</em>